vert-x3/vertx-zookeeper

src/main/java/io/vertx/spi/cluster/impl/zookeeper/ZKAsyncMap.java
This PR make test could be pass.
=> do not replace null value if previous value is null.

src/main/java/io/vertx/spi/cluster/impl/zookeeper/ZKAsyncMap.java, src/main/java/io/vertx/spi/cluster/impl/zookeeper/ZKAsyncMultiMap.java, src/main/java/io/vertx/spi/cluster/impl/zookeeper/ZKMap.java
=> fix problem that cause #10

pom.xml, src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java
Replace ExtendClusterManager interface by ClusterManager.
=> Bump version change cluster interface

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java
=> add new constructor with config path

pom.xml, src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMultiMap.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKMap.java, src/test/java/io/vertx/spi/cluster/zookeeper/MockZKCluster.java, src/test/java/io/vertx/test/core/ZKAsyncMultiMapTest.java, src/test/java/io/vertx/test/core/ZKClusteredAsynchronousLockTest.java, src/test/java/io/vertx/test/core/ZKClusteredComplexHATest.java, src/test/java/io/vertx/test/core/ZKClusteredEventbusTest.java, src/test/java/io/vertx/test/core/ZKClusteredHATest.java, src/test/java/io/vertx/test/core/ZKClusteredSharedCounterTest.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java
Some test eventbus always show timeout, fix it by send message delay.
=> Fix test timeout

src/test/java/io/vertx/test/core/ZKClusteredEventbusTest.java
=> fix case ReplyExceptionSubclass timeout

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKMap.java
=> sync node data before check exist.

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMap.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMultiMap.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKMap.java
Make a refactor that replace nest handler in this project by CompositeFuture.
=> refactor some nest handler by CompositeFuture.

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java, src/test/resources/zookeeper.json
As issue #33 said, we changes locks life to vertx cluster instead of whole JVM
=> fix lock free issue

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMap.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java
As subject :)
Signed-off-by: stream stream1984@gmail.com
=> fix put TTL issue.

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/AsyncMapTTLMonitor.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMap.java, src/test/java/io/vertx/spi/cluster/zookeeper/MockZKCluster.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java
=> fix ttl bug and refactor TTL mechanism

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java
=> Test locking on same Vert.x instance

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKSyncMap.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java
=> fix inner class scope

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMultiMap.java, src/test/java/io/vertx/spi/cluster/zookeeper/MockZKCluster.java
=> AsyncMultiMap startup is async we have to wait state become inited.

pom.xml, src/test/java/io/vertx/spi/cluster/zookeeper/MockZKCluster.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java
=> bump curator version to 2.11.1

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMap.java
=> confirm curator have started.

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMultiMap.java
See eclipse/vert.x#1848
I couldn't add the FaultToleranceTest since tests in this CM use a mock ZK server
=> Fault tolerance for event bus subscription

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKMap.java, src/test/java/io/vertx/test/core/ZKClusteredWideMapTest.java
@cescoffier Would you have a look? 
thanks.
=> fix issue [#4]

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKAsyncMultiMap.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKMap.java, src/test/java/io/vertx/test/core/ZKClusteredEventbusTest.java
=> fix some inconsistency methods in asyncMultiMap

src/test/java/io/vertx/test/core/ZKClusteredEventbusTest.java
=> delay verticle node start.

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKSyncMap.java
add serialVersionUID to nested class of KeyValue.
=> add serialVersionsUID

.travis.deploy.artifacts.sh, .travis.maven.settings.xml, .travis.yml
=> add CI travis

src/main/java/io/vertx/spi/cluster/zookeeper/impl/ZKSyncMap.java
Add ZK's sync operation to SyncMap, since vertx-zookeeper would throw node doesn't exist  in pressure test.
=> add zk sync action for SyncMap operation.

pom.xml, src/main/java/io/vertx/spi/cluster/zookeeper/impl/SubsMapHelper.java, src/test/java/io/vertx/core/shareddata/ZKClusteredAsyncMapTest.java, src/test/java/io/vertx/ext/web/sstore/ZKClusteredSessionHandlerTest.java, src/test/java/io/vertx/spi/cluster/zookeeper/MockZKCluster.java
Address problem explained in #117.
=> Update SubsMapHelper to discern local vs global addresses

src/main/java/io/vertx/spi/cluster/zookeeper/impl/SubsMapHelper.java
Fixes #120
Otherwise, a `ConcurrentModificationException` could be thrown if a local consumer is registered or unregistered at the same time.
=> Synchronize access to localSubs list when traversing

src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/ConfigUtil.java
=> Load config as described in the doc

src/main/asciidoc/index.adoc, src/main/java/io/vertx/spi/cluster/zookeeper/ZookeeperClusterManager.java, src/main/java/io/vertx/spi/cluster/zookeeper/impl/RetryPolicyHelper.java, src/main/resources/default-zookeeper.json, src/test/java/io/vertx/core/ProgrammaticZKClusterManagerTest.java, src/test/java/io/vertx/spi/cluster/zookeeper/RetryPolicyTest.java
=> Add a way to configure the retry policy using json file
